### ISSUE TITLE
Addition of new RubyGem, "pastee", to Wiki

### ISSUE THREAD

**Issue by elifoster** [pastee/pastee#2]
I have created a Ruby Gem for interacting with Pastee, simply called "pastee". Its source is [on GitHub](https://github.com/elifoster/pastee-rb), and is available through [RubyGems](https://rubygems.org/gems/pastee). If this could get added to the list of "Libraries interfacing with Pastee" on the Wiki, that'd be splendid!

**Comment by nikkiii** [comment]
This is quite nice, thanks!

Any chance you could write this for the upcoming new api on the beta? Information can be found [here](http://beta.paste.ee/apidoc/) and [here](http://beta.paste.ee/wiki/API:Keys), then all that needs to be done is swap the url when it's released to `api.paste.ee`

**Comment by elifoster** [comment]
Sure! I'll work on that today.
