### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by elifoster** [pastee/pastee#3]
So, any request I do, POST or GET, returns no response. This happens both with my test code, as well as through the API documentation's "Try it out" feature.

**Comment by nikkiii** [comment]
This might be an issue with swagger, it's a very confusing documentation system. I'll try to move it over to a better doc system later.

**Comment by elifoster** [comment]
That doesn't really explain my test code having this result though.

**Comment by nikkiii** [comment]
Looks like I forgot to include the throttle class when throttling paste submissions, should work now.

**Comment by nikkiii** [comment]
See if this is maybe better than the other docs:
http://pastee.github.io/docs/

Still a work in progress, and URLs are for now `api.beta.paste.ee` instead of `api.paste.ee`

**Comment by elifoster** [comment]
I don't have a lot of time to look at it right now, but I'll get to it later tonight or tomorrow. Although taking a brief look at it, I do notice one inconsistency. In the Authentication example, the header is called "Authorization", however in the documentation it is "X-Auth-Token". You might want to clear up this confusion.

**Comment by nikkiii** [comment]
I've fixed that and moved the docs off `/slate` to `/docs`, which might take a minute to update. Thanks!
