### ISSUE TITLE
Sections field required error

### ISSUE THREAD

**Issue by elifoster** [pastee/pastee#4]
Whenever I submit a request to api.beta.paste.ee, I get a "sections field is required error", despite me setting the sections field.

**Comment by nikkiii** [comment]
What does the raw request look like?

Sections is an array field, and has at least one array with a child, so it'd look something like this:

```
sections[][contents]=test
```

Or, using JSON:

``` json
{
    "sections": [
        { "name" : "Test", "contents" : "test" }
    ]
}
```

**Comment by elifoster** [comment]
Here is the Hash object I pass as the parameters.

``` ruby
{
  :description => "Test description",
  :sections => [
    {
      :name => "Name",
      :syntax => "autodetect",
      :contents => "Test"
    }
  ],
  :encrypted => 0
}
```

**Comment by nikkiii** [comment]
Hm... All I can say is make sure it's serializing it correctly, maybe ruby isn't handling the nested objects or something. I just tested it and it works fine from another program interfacing with the beta api.

You can also POST with a JSON body, which might be an easier alternative to ensure the data is intact

**Comment by elifoster** [comment]
The full code is:

``` ruby
    check_beta
    uri = URI.parse(URI.encode("#{@url}/v1/pastes"))
    params = {
      description: description,
      sections: [
        {
          name: name,
          syntax: language,
          contents: paste
        }
      ]
    }
    header = { 'X-Auth-Token' => @key, 'Content-Type' => 'application/json' }
    params[:encrypted] = encrypted ? 1 : 0
    p params
    response = @client.post(uri, params, header)
    json = JSON.parse(response.body)
    p json
```

and it uses nahi/httpclient so it should work fine. I guess I could try converting the params to JSON first.

**Comment by nikkiii** [comment]
Looks like you're trying to send the content-type as json which would cause the server to try to decode json. Make sure you're either encoding it or it encodes it to json for you, otherwise it should be the encoded form data type.

**Comment by elifoster** [comment]
Without that I get the following response:

``` html
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>
            /* Copyright (c) 2010, Yahoo! Inc. All rights reserved. Code licensed under the BSD License: http://developer.yahoo.com/yui/license.html */
            html{color:#000;background:#FFF;}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0;}table{border-collapse:collapse;border-spacing:0;}fieldset,img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}li{list-style:none;}caption,th{text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;}q:before,q:after{content:'';}abbr,acronym{border:0;font-variant:normal;}sup{vertical-align:text-top;}sub{vertical-align:text-bottom;}input,textarea,select{font-family:inherit;font-size:inherit;font-weight:inherit;}input,textarea,select{*font-size:100%;}legend{color:#000;}

            html { background: #eee; padding: 10px }
            img { border: 0; }
            #sf-resetcontent { width:970px; margin:0 auto; }
                        .sf-reset { font: 11px Verdana, Arial, sans-serif; color: #333 }
            .sf-reset .clear { clear:both; height:0; font-size:0; line-height:0; }
            .sf-reset .clear_fix:after { display:block; height:0; clear:both; visibility:hidden; }
            .sf-reset .clear_fix { display:inline-block; }
            .sf-reset * html .clear_fix { height:1%; }
            .sf-reset .clear_fix { display:block; }
            .sf-reset, .sf-reset .block { margin: auto }
            .sf-reset abbr { border-bottom: 1px dotted #000; cursor: help; }
            .sf-reset p { font-size:14px; line-height:20px; color:#868686; padding-bottom:20px }
            .sf-reset strong { font-weight:bold; }
            .sf-reset a { color:#6c6159; cursor: default; }
            .sf-reset a img { border:none; }
            .sf-reset a:hover { text-decoration:underline; }
            .sf-reset em { font-style:italic; }
            .sf-reset h1, .sf-reset h2 { font: 20px Georgia, "Times New Roman", Times, serif }
            .sf-reset .exception_counter { background-color: #fff; color: #333; padding: 6px; float: left; margin-right: 10px; float: left; display: block; }
            .sf-reset .exception_title { margin-left: 3em; margin-bottom: 0.7em; display: block; }
            .sf-reset .exception_message { margin-left: 3em; display: block; }
            .sf-reset .traces li { font-size:12px; padding: 2px 4px; list-style-type:decimal; margin-left:20px; }
            .sf-reset .block { background-color:#FFFFFF; padding:10px 28px; margin-bottom:20px;
                -webkit-border-bottom-right-radius: 16px;
                -webkit-border-bottom-left-radius: 16px;
                -moz-border-radius-bottomright: 16px;
                -moz-border-radius-bottomleft: 16px;
                border-bottom-right-radius: 16px;
                border-bottom-left-radius: 16px;
                border-bottom:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
            }
            .sf-reset .block_exception { background-color:#ddd; color: #333; padding:20px;
                -webkit-border-top-left-radius: 16px;
                -webkit-border-top-right-radius: 16px;
                -moz-border-radius-topleft: 16px;
                -moz-border-radius-topright: 16px;
                border-top-left-radius: 16px;
                border-top-right-radius: 16px;
                border-top:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
                overflow: hidden;
                word-wrap: break-word;
            }
            .sf-reset a { background:none; color:#868686; text-decoration:none; }
            .sf-reset a:hover { background:none; color:#313131; text-decoration:underline; }
            .sf-reset ol { padding: 10px 0; }
            .sf-reset h1 { background-color:#FFFFFF; padding: 15px 28px; margin-bottom: 20px;
                -webkit-border-radius: 10px;
                -moz-border-radius: 10px;
                border-radius: 10px;
                border: 1px solid #ccc;
            }
        </style>
    </head>
    <body>
                    <div id="sf-resetcontent" class="sf-reset">
                <h1>Whoops, looks like something went wrong.</h1>

            </div>
    </body>
</html>
```

which causes a parser error in the JSON gem, obviously. I can't really see what I'm doing wrong, as I have the hash set up as the documentation describes.

**Comment by nikkiii** [comment]
Looks like that was an error in the response due to a malformed body (it expects sections to be keyed by an integer, relating to an index)

Try redirecting the request at http://requestb.in/ and sharing the request body.

**Comment by elifoster** [comment]
Raw body: `Description=Description&sections=%7B%3Aname%3D%3E%22Name%22%2C+%3Asyntax%3D%3E%22autodetect%22%2C+%3Acontents%3D%3E%22Content%22%7D`
POST parameters: 

```
sections: {:name=>"Name", :syntax=>"autodetect", :contents=>"Content"}

description: Description
```

Content type: `application/x-www-form-urlencoded`

**Comment by nikkiii** [comment]
Looks like the data is encoded wrong, I don't think that library/gem likes the data format/arrays.

Try encoding it into json with the JSON gem, then sending it with the content type set to `application/json`

**Comment by elifoster** [comment]
That's really weird. Converting it to a string (technically `to_json` converts it to a JSON, but the actual object is a String) seems to have worked. What I find strange is that using basically identical code, aside from formatting and stuff for the API, worked on the old Pastee API, as well as a bunch of other APIs, such as Weather Underground, MediaWiki, and Fishbans.

Although, it doesnt seem like the X-Auth-Token header did anything, as I still have no pastes in my account.

**Comment by nikkiii** [comment]
The old API didn't use any nested objects (in this case, sections), which is why it worked fine.

The application keys just give access to an application, in order to have it add pastes to your account it now requires a UserApplication key. More information about keys is available here: https://beta.paste.ee/wiki/API:Keys

**Comment by elifoster** [comment]
That makes sense. Looks like I've got it working now. Now to add interfaces for all the other APIs.

**Comment by elifoster** [comment]
I actually don't have it working. The API is claiming that the section syntax is invalid. Here's what the params look like (formatted so it's easier for you to read):

```
"{
  \"description\":\"Description\",
  \"sections\": [
    {
      \"name\":\"Name\",
      \"syntax\":\"Ruby\",
      \"contents\":\"Content\"
    }
  ],
  \"encrypted\":0
}"
```

I'm just gonna say that there's definitely something wrong with how the API accepts requests, because I've never had this much trouble setting up an interface to a web API using HTTPClient, and I have about 5 other gems that do this.

**Comment by nikkiii** [comment]
`Ruby` is not a valid syntax, the syntax definition is considered the 'short' version of it (as listed below). In this case, it would be just `ruby`.

https://beta.paste.ee/p/3tO7r

**Comment by elifoster** [comment]
Okay, I'll go ahead and make a constant for all the valid syntaxes so that people don't make that same mistake :)

**Comment by elifoster** [comment]
All's good now.
