### ISSUE TITLE
Getting paste always errors with "No application key"

### ISSUE THREAD

**Issue by elifoster** [pastee/pastee#5]
I've tried using both key types, and neither of them work for getting pastes. The response is always

``` ruby
{"errors"=>[{"code"=>1, "message"=>"No application key supplied."}], "success"=>false}
```

**Comment by nikkiii** [comment]
Sorry! Noticed this issue last night when testing the new node api, if you were using the `Access-Key` header or Authorization (User being the key), it wasn't setup to properly detect that. It could have also affected other methods. There's a reason this is the beta and not actual release site yet :c

Try it and let me know!

**Comment by elifoster** [comment]
I have been using X-Auth-Token, as that's what the API says to use in most cases (sometimes it says Authorization, I've yet to see Access-Key). Using any of these three auth headers makes no difference. If needed, the code is in my [repo](https://github.com/elifoster/pastee-rb/blob/beta-api/lib/pastee_beta.rb#L113-L131).

**Comment by nikkiii** [comment]
Looks like it's a problem in your code here, according to the HTTPClient docs the second param is `query` (being the query data), which is what you're passing the headers as.

I did get it working locally by doing this instead:

``` ruby
response = @client.get(uri, :header => header)
```

**Comment by elifoster** [comment]
:scream_cat: I swear I had the second parameter as nil in that method! By the way, in case you use or plan on using Ruby, `:header => header` is old syntax for hashes, the new syntax is `header: header`, unless the key is a string, in which case it must be `'header' => header`. Works now, thanks.
