### ISSUE TITLE
Listing pastes returns "nothing"

### ISSUE THREAD

**Issue by elifoster** [pastee/pastee#6]
When I try to list pastes with the API, I get no results. Here's the raw response:

``` ruby
{"total"=>0, "per_page"=>25, "current_page"=>1, "last_page"=>0, "next_page_url"=>nil, "prev_page_url"=>nil, "from"=>1, "to"=>0, "data"=>[], "success"=>true}
```

**Comment by elifoster** [comment]
So, now whenever I do it, regardless of which API key I use, it states that the application key is invalid.

**Comment by elifoster** [comment]
Yo @nikkiii Any word on why this would be happening?

**Comment by nikkiii** [comment]
As far as I can tell there's nothing wrong with the API, you're either using an Application key for a UserApplication operation, or the key is actually invalid.

**Comment by elifoster** [comment]
I've tried using both application key types, and neither work, so I'd guess the key is actually invalid. Though I'm getting them directly from https://beta.paste.ee/account/api
