### ISSUE TITLE
How does Auto Detect actually work?

### ISSUE THREAD

**Issue by elifoster** [pastee/pastee#8]
I'm very interested in hearing how the Auto Detect thing actually works. I use Beta Pastee a lot for things like post drafts and in-dev changelogs, and usually just use the "Auto Detect" option. I've gotten some pretty strange results. Do you use an existing library to detect the language? If so which one?

**Comment by nikkiii** [comment]
It always uses highlight.js, and it's always going to be a best-guess type of thing, no matter which library I use. I have been thinking about writing specific rules to check for edge cases on top of the auto detection, which currently works just by figuring out the type before it renders the code, but in this case it might be better to figure it out before submitting the paste and let the user correct it...

**Comment by elifoster** [comment]
Ah. If only highlight.js supported mediawiki syntax...

**Comment by nikkiii** [comment]
It can if there's a plugin for it, just look around

**Comment by elifoster** [comment]
I'm gonna look into submitting a PR to add simple mediawiki syntax to it, since they no longer add languages.
